### ISSUE TITLE
Alloy OpenApi module import issue

### ISSUE THREAD

**Issue by scala-impala** [disneystreaming/alloy#33]
When adding "com.disneystreaming.alloy:alloy-openapi:x.x.x" as
`val alloyOpenApi = "com.disneystreaming.alloy" % "alloy-openapi" % AppVersions.alloy`
sbt fails to retrieve the module. After I took a look at maven central it seems it is only published with the _2.12 and _2.13 suffixes.

**Comment by daddykotex** [comment]
From the snippet you share it seems like your working with Scala, so: `val alloyOpenApi = "com.disneystreaming.alloy" %% "alloy-openapi" % AppVersions.alloy` should work.

**Comment by daddykotex** [comment]
But that essentially mean that the README is invalid: https://github.com/disneystreaming/alloy#using-alloy

**Comment by daddykotex** [comment]
Where you able to pull the dependency?

**Comment by scala-impala** [comment]
Hi @daddykotex still seeing the same issue after adding the second "%" using `0.1.4` as the value for `AppVersions.alloy`. However don't have any issues when only pulling the alloy core dependency.

**Comment by Baccata** [comment]
@scala-impala what version of the language are you using ?

**Comment by scala-impala** [comment]
@Baccata this is with Scala 3.2.0

**Comment by Baccata** [comment]
@scala-impala right, it'd have. been good to start there. And may I ask your use-case ? This module is typically used at build-time with build-tools. Cross compiling between 2.12 and 2.13 lets us support both SBT and mill. We're not necessarily adversed to cross-compiling to more targets, but we'd like for an explanation of the need before we do.

**Comment by scala-impala** [comment]
@Baccata I see, thanks, that makes sense now. I don't know a lot about build tools and SBT and as long as it works I don't touch it and don't try to ask too many questions, but will try do so some more effort before opening useless issues :) In any case, I evetually managed to add it like this:
`    val alloyOpenApi = ("com.disneystreaming.alloy" % "alloy-openapi" % AppVersions.alloy cross CrossVersion.for3Use2_13)
    .exclude("org.typelevel", "cats-core_2.13")
    .exclude("org.typelevel", "cats-kernel_2.13")
    .exclude("org.scala-lang.modules", "scala-collection-compat_2.13")`

**Comment by kubukoz** [comment]
The issue wasn't useless, I think we should just talk it out to understand why you find yourself stuck with it in the first place :)

The workaround with `exclude` may work now, but it's not something I'd recommend long term. Echoing @Baccata's comment, could you share more about your usecase? I feel like you shouldn't need this at runtime.
